// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate-installments": {
            "post": {
                "description": "Calculate Installment Simulation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Calculate Installment Simulation",
                "parameters": [
                    {
                        "description": "Calculation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.CalculateInstallmentsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/finance_internal_model.InstallmentSimulation"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/limits": {
            "get": {
                "description": "Get User Limits",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Get User Limits",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/finance_internal_model.UserLimit"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/submit-financing": {
            "post": {
                "description": "Submit Finance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Submit Finance",
                "parameters": [
                    {
                        "description": "Submit Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.SubmitFinancingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.SubmitFinancingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tenors": {
            "get": {
                "description": "Get Tenor List",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Get Tenor List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/finance_internal_model.ListTenor"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/finance_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "finance_internal_model.CalculateInstallmentsRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "finance_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "finance_internal_model.InstallmentSimulation": {
            "type": "object",
            "properties": {
                "monthly_installment": {
                    "type": "number"
                },
                "tenor": {
                    "type": "integer"
                },
                "total_margin": {
                    "type": "number"
                },
                "total_payment": {
                    "type": "number"
                }
            }
        },
        "finance_internal_model.ListTenor": {
            "type": "object",
            "properties": {
                "tenor_value": {
                    "type": "integer"
                }
            }
        },
        "finance_internal_model.ScheduleDetail": {
            "type": "object",
            "properties": {
                "due_date": {
                    "type": "string"
                },
                "installment_amount": {
                    "type": "number"
                }
            }
        },
        "finance_internal_model.SubmitFinancingRequest": {
            "type": "object",
            "required": [
                "amount",
                "facility_limit_id",
                "start_date",
                "tenor",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "facility_limit_id": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "tenor": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "finance_internal_model.SubmitFinancingResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "facility_limit_id": {
                    "type": "integer"
                },
                "monthly_installment": {
                    "type": "number"
                },
                "schedule": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/finance_internal_model.ScheduleDetail"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "tenor": {
                    "type": "integer"
                },
                "total_margin": {
                    "type": "number"
                },
                "total_payment": {
                    "type": "number"
                },
                "user_facility_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "finance_internal_model.UserLimit": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "limit_amount": {
                    "type": "number"
                },
                "limit_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Finance System API",
	Description:      "API for finance simulation system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
